name: 'StructureSmith Action'
description: 'Automatically generate project templates for repositories'
author: 'cbrgm'

inputs:
  config:
    description: 'Path to the YAML configuration file'
    required: false
  project:
    description: 'Specify a project to render'
    required: true
  output:
    description: 'Output path prefix for generated files'
    default: "./out"
    required: false
  templates:
    description: 'Directory where template files are stored'
    default: "./templates"
    required: false

runs:
  using: docker
  image: 'docker://ghcr.io/cbrgm/structuresmith:v1'
  args:
    - --config
    - ${{ inputs.config }}
    - --output
    - ${{ inputs.output }}
    - --templates
    - ${{ inputs.templates }}
    - ${{ inputs.project }}

branding:
  icon: code
  color: blue
