templateGroups:
  commonGitFiles:
    - filename: ".gitignore"
      sourceFile: "gitignore.tmpl"
    - filename: "LICENSE"
      sourceFile: "LICENSE"
    - filename: "Dockerfile"
      sourceUrl: "https://raw.githubusercontent.com/cbrgm/promcheck/main/Dockerfile"

  goSpecificFiles:
    - filename: ".golangci.yml"
      sourceFile: "golangci.tmpl"

repositories:
  - name: "example/repo1"
    groups:
      - groupName: "commonGitFiles"
        values:
          Author: "Some Author"
          Year: "2023"
      - groupName: "goSpecificFiles"
        values:
          golangciVersion: "1.53.x"

  - name: "example/repo2"
    groups:
      - groupName: "commonGitFiles"
        values:
          Author: "Chris Bargmann"
          Year: "2023"

  - name: "example/repo3"
    files:
      - filename: "far.txt"
        content: |
          this is some content {{ .Foo }}
        values:
          Foo: "Bar"
    groups:
      - groupName: "commonGitFiles"
        values:
          Author: "Chris Bargmann"
          Year: "2023"

  - name: "some-project"
    files:
      - filename: "far.txt"
        content: |
          this is some content {{ .Foo }}
        values:
          Foo: "Bar"
    groups:
      - groupName: "commonGitFiles"
        values:
          Author: "Chris Bargmann"
          Year: "2023"
