name: Demo Workflow

on:
  workflow_dispatch:

jobs:
  render-all-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Render All Files
        uses: cbrgm/structuresmith@v1
        with:
          # required
          project: example/repo1
          # optional
          config-file: ./anvil.yml
          output-path: ./out
          templates-dir: ./templates
